---
name: InventoryClear
author: narapon
version: 1.0.0
api: 3.4.0
main: Narapon\InventoryClear\Main
commands:
  ic:
    description: §9<OP>インベントリ削除
    permission: clearinventory
permissions:
  clearinventory.own:
    description: Allow player to clear their own inventory
    default: op
  clearinventory.other:
    description: Allow player to clear players' inventories
    default: op
...
